version: '3'
services: 
  database: 
    image: 'mongo'
    container_name: 'mongo-test'
    environment: 
      - MONGO_INITDB_DATABASE=mongo-test
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'